In [28]:
import numpy as np
seed = 47

In [33]:
#Task 1
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [34]:
#Task 2
x = np.zeros((5,5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [35]:
[[j for j in range(5)] for i in range(5)]

[[0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4]]

In [36]:
#Task 3
x = np.random.random((3,3,3))
x

array([[[0.32229765, 0.85991312, 0.16569212],
        [0.27758389, 0.65568704, 0.63376639],
        [0.22769651, 0.59028271, 0.39045553]],

       [[0.95878376, 0.4545075 , 0.83261686],
        [0.48130988, 0.44585728, 0.1083505 ],
        [0.36420098, 0.53988703, 0.08840358]],

       [[0.56711873, 0.71745161, 0.48366247],
        [0.96124443, 0.1748947 , 0.69820116],
        [0.48568174, 0.60035711, 0.61728005]]])

In [37]:
#Task 4
x = np.ones((4, 4))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [38]:
#Task 5
x = np.random.random(10)
x

array([0.33961289, 0.92854648, 0.70371331, 0.57245122, 0.2474747 ,
       0.33510683, 0.88965592, 0.6809733 , 0.5200319 , 0.92339713])

In [39]:
sorted(x, reverse=True)

[0.9285464768336167,
 0.9233971301642717,
 0.8896559205855783,
 0.7037133061392035,
 0.6809733042164904,
 0.5724512168456742,
 0.520031898088922,
 0.3396128941297799,
 0.3351068340092854,
 0.24747469682713719]

In [42]:
#Task 6
a = np.random.random((2, 2, 2))
print(a)
a.shape

[[[0.32397041 0.91142575]
  [0.26159604 0.43058636]]

 [[0.98744009 0.96801867]
  [0.58620942 0.4463849 ]]]


(2, 2, 2)

In [2]:
import pandas as pd

In [6]:
#Task 7-8
df = pd.read_csv('adult.csv')
df.head(2)

age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K

In [7]:
df.tail(2)

age     workclass  education_num      marital_status       occupation  \
45220   44       Private             13            Divorced     Adm-clerical   
45221   35  Self-emp-inc             13  Married-civ-spouse  Exec-managerial   

      relationship   race gender  hours_per_week native_country  capital  \
45220    Own-child  Other   Male              40  United-States     5455   
45221      Husband  White   Male              60  United-States        0   

      income_status  
45220         <=50K  
45221          >50K

In [8]:
df.shape

(45222, 12)

In [10]:
df.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [43]:
#Task 9
from sklearn import preprocessing

df2 = pd.read_csv('df_test.csv')

minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))

X_scaled = minmax_scale.fit_transform(df2['sepal_length_cm'])

X_scaled

ValueError: Expected 2D array, got 1D array instead:
array=[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

Я не знаю почему так выходит, но так выходит
Я прогнал на пробных данных ниже и все прекрасно получается...

In [39]:
df2

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [40]:
df3 = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))

X_scaled = minmax_scale.fit_transform(df3)

X_scaled

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [41]:
scaler = preprocessing.StandardScaler()

X2_scaled = scaler.fit_transform(df3)

X2_scaled

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])